[package]
name = "gitru"
version = "0.0.1"
edition = "2021"
authors = ["xiyi <xiyixiaodao@outlook.com>"]
description = "Git commit message validator with configurable rules"
license = "MIT"
repository = "https://github.com/xiyixiaodao/gitru"
keywords = ["git", "commit", "commit-msg", "hook", "validation"]
categories = ["development-tools"]

[profile.release]
# Enable Link-Time Optimization
lto = true

[dependencies]
clap = { version = "4.5", features = ["derive"] }
tracing = "0.1.41"
tracing-subscriber = { version = "0.3.19", features = [
    "local-time",
    "env-filter",
] }
colored = "3.0.0"
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.9"
winapi = { version = "0.3", features = [
    "consoleapi",
    "processenv",
    "wincon",
    "winbase",
] }
